# Generated by Django 5.2.7 on 2025-11-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('i_year_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('ii_year_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('iii_year_subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(db_index=True, max_length=128)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')])),
                ('extra', models.JSONField(blank=True, null=True)),
                ('uploaded_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seating.uploadedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Seating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III')])),
                ('roll', models.CharField(blank=True, max_length=128)),
                ('row_index', models.PositiveIntegerField()),
                ('col_index', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seating.room')),
            ],
            options={
                'indexes': [models.Index(fields=['exam_date', 'room'], name='seating_sea_exam_da_dbe3b6_idx')],
            },
        ),
    ]
